<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="REST"
    nsURI="http://rest/1.0" nsPrefix="REST">
  <eClassifiers xsi:type="ecore:EClass" name="RESTService" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" lowerBound="1"
        upperBound="-1" eType="#//Resource" containment="true" eOpposite="#//Resource/belongsTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" lowerBound="1"
        eType="#//Language"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" lowerBound="1"
        eType="#//API" eOpposite="#//API/services"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" lowerBound="1"
        upperBound="-1" eType="#//Method" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" lowerBound="1"
        eType="#//RESTService" eOpposite="#//RESTService/resources"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" lowerBound="1"
        eType="#//HTTPRequest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responses" lowerBound="1"
        eType="#//HTTPResponse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hooks" upperBound="-1"
        eType="#//Hook" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTTPRequest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HTTPResponse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediaType" lowerBound="1"
        eType="#//MediaType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JSONMediaType" eSuperTypes="#//MediaType"/>
  <eClassifiers xsi:type="ecore:EClass" name="XMLMediaType" eSuperTypes="#//MediaType"/>
  <eClassifiers xsi:type="ecore:EClass" name="HTMLMediaType" eSuperTypes="#//MediaType"/>
  <eClassifiers xsi:type="ecore:EClass" name="TEXTMediaType" eSuperTypes="#//MediaType"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateMethod" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReadMethod" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateMethod" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteMethod" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hook">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="API">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" lowerBound="1"
        eType="#//System" eOpposite="#//System/APIs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" lowerBound="1"
        upperBound="-1" eType="#//RESTService" containment="true" eOpposite="#//RESTService/belongsTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="#//RESTService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="database" upperBound="-1"
        eType="#//DataBase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="#//RESTService"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataBase" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="APIs" lowerBound="1" upperBound="-1"
        eType="#//API" containment="true" eOpposite="#//API/belongsTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Language" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Java" eSuperTypes="#//Language"/>
  <eClassifiers xsi:type="ecore:EClass" name="PHP" eSuperTypes="#//Language"/>
  <eClassifiers xsi:type="ecore:EClass" name="JavaScript" eSuperTypes="#//Language"/>
  <eClassifiers xsi:type="ecore:EClass" name="MySql" eSuperTypes="#//DataBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="SqlServer" eSuperTypes="#//DataBase"/>
</ecore:EPackage>
